### ISSUE TITLE
testy

### ISSUE THREAD

**Issue by pwr-mszczepanik** [Ritzel10/Bmi#1]
https://github.com/Ritzel10/Bmi/blob/693747b71459c796c5b13a84f0bf567f657b5c24/app/src/test/java/pl/edu/pwr/nr238367/bmichojnacki2/BmiCategoryTest.java#L10

Testy powinny byc rozbite i testowac jedna rzecz na raz w tym miejscu starczy ze jeden z asertow nie przejdzie i test bedzie czerwony, na dodatek pozostale po failujacym assercie nie zostana wykonane

**Comment by chojnacki-marcin** [comment]
Czy dla każdego asserta powinien być osobny test, czy mogą być testy dla każdej kategorii?
